# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angelina Calderon
email: angelina@angelinacalderon.com
description: >
  Angelina Calderon has over six years of experience growing businesses
  by driving customer success, delivering innovative products
  and services, and strengthening processes to improve product delivery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angelinacalderon.com" # the base hostname & protocol for your site
twitter_username: alinapaz
github_username:  alinapaz

permalink: "/:year/:month/:title"
paginate: 10
paginate_path: "/page/:num/"
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-feed
